package visao;

import java.util.Random;
import javax.swing.JOptionPane;
import modelador.GeradorSenha;
import modelador.JDBCUsuario;

public class Cadastrar_Funcionario extends javax.swing.JFrame {

    JDBCUsuario usuarioNovo;
    Principal p;
    
    /**
     * Creates new form Cadastrar_Funcionario
     */
    public Cadastrar_Funcionario(JDBCUsuario usuarioNovo, Principal p) {
        initComponents();
        this.usuarioNovo = usuarioNovo;
        this.p = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Name = new javax.swing.JLabel();
        edt_nome = new javax.swing.JTextField();
        combo_tipo = new javax.swing.JComboBox<>();
        btn_cadastrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(550, 400));
        setName(""); // NOI18N
        setUndecorated(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(550, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(550, 400));
        jPanel1.setLayout(null);

        lbl_Name.setText("Nome:");
        jPanel1.add(lbl_Name);
        lbl_Name.setBounds(50, 130, 40, 20);
        jPanel1.add(edt_nome);
        edt_nome.setBounds(90, 130, 326, 22);

        combo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionário", "Administrador" }));
        combo_tipo.setSelectedIndex(-1);
        jPanel1.add(combo_tipo);
        combo_tipo.setBounds(200, 160, 130, 22);

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cadastrar);
        btn_cadastrar.setBounds(110, 280, 130, 40);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar);
        btn_cancelar.setBounds(290, 280, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imgs/Tela Agendar Consulta.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        if(edt_nome.getText().equals("") || combo_tipo.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(null, "Campo(s) vazio(s)");
        else{
            usuarioNovo.cadastrarUsuario(combo_tipo.getSelectedIndex(), edt_nome.getText(), GeradorSenha.gerarSenha(new Random().nextInt(8)));
            p.carregarTabelaFuncionarios();
            dispose();
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox<String> combo_tipo;
    private javax.swing.JTextField edt_nome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Name;
    // End of variables declaration//GEN-END:variables
}
